import type { TerminalCapabilities } from "../platform/terminal/capabilities.js";

export const TRUE_COLOR_TOKENS = {
  backgroundOuter: "#0B0B0B",
  background: "#101010",
  elevated: "#141414",
  surface1: "#161616",
  surface2: "#1C1C1C",
  surface3: "#262626",
  surface4: "#313131",
  foreground: "#E7E7E7",
  foregroundOnSurface: "#E8E8E8",
  secondary: "#9F9F9F",
  secondaryOnSurface: "#A4A4A4",
  muted: "#707070",
  mutedOnSurface: "#777777",
  disabled: "#555555",
  decoration: "#1E2529",
  borderSubtle: "#242424",
  border: "#2D2D2D",
  borderStrong: "#3B3B3B",
  primary: "#0077FF",
  primaryText: "#3D98FF",
  accent: "#7C8DB8",
  hover: "#202020",
  selected: "#18293C",
  focus: "#162E49",
  infoBackground: "#142538",
  warningBackground: "#382A18",
  dangerBackground: "#351B24",
  success: "#04D793",
  warning: "#FFAA3B",
  danger: "#FF4B7B",
  kunpeng: "#ED1C24",
  kunpengSecondary: "#C9C9C9",
  copyBlue: ["#052C75", "#094CCD", "#3C7CF6", "#76A3F9", "#B1CAFC"],
  violet: ["#3F0675", "#6E0ACD", "#9B3CF6", "#B977F9", "#D7B1FB"],
  accumOrange: ["#773303", "#A44604", "#D15905", "#F96A06", "#FA8838", "#FBAB74", "#FDCFAF"],
  ubGreen: ["#4D7209", "#86C70F", "#B3F141", "#CAF57A", "#E1F9B3"],
  mteAmber: ["#713F12", "#CA8A04", "#F4CB22", "#FBDC59", "#FDEB9D"],
  cpu: ["#4D7209", "#86C70F", "#B3F141", "#CAF57A"],
  npu: ["#3F0675", "#6E0ACD", "#9B3CF6", "#B977F9"],
  memory: ["#773303", "#D15905", "#FA8838", "#FBAB74"],
  io: ["#713F12", "#CA8A04", "#F4CB22", "#FBDC59"],
} as const;

const ANSI16_TOKENS = {
  ...TRUE_COLOR_TOKENS,
  backgroundOuter: "black",
  background: "black",
  elevated: "black",
  surface1: "black",
  surface2: "black",
  surface3: "brightBlack",
  surface4: "brightBlack",
  foreground: "white",
  foregroundOnSurface: "white",
  secondary: "brightBlack",
  secondaryOnSurface: "white",
  muted: "brightBlack",
  mutedOnSurface: "brightBlack",
  disabled: "brightBlack",
  decoration: "brightBlack",
  borderSubtle: "brightBlack",
  border: "brightBlack",
  borderStrong: "white",
  primary: "blue",
  primaryText: "brightBlue",
  accent: "brightBlue",
  hover: "brightBlack",
  selected: "blue",
  focus: "blue",
  infoBackground: "blue",
  warningBackground: "yellow",
  dangerBackground: "red",
  success: "brightGreen",
  warning: "brightYellow",
  danger: "brightRed",
  kunpeng: "red",
  kunpengSecondary: "white",
  copyBlue: ["blue", "blue", "brightBlue", "brightBlue", "white"],
  violet: ["magenta", "magenta", "brightMagenta", "brightMagenta", "white"],
  accumOrange: [
    "yellow",
    "yellow",
    "yellow",
    "brightYellow",
    "brightYellow",
    "brightYellow",
    "white",
  ],
  ubGreen: ["green", "green", "brightGreen", "brightGreen", "white"],
  mteAmber: ["yellow", "yellow", "brightYellow", "brightYellow", "white"],
  cpu: ["green", "green", "brightGreen", "brightGreen"],
  npu: ["magenta", "magenta", "brightMagenta", "brightMagenta"],
  memory: ["yellow", "yellow", "brightYellow", "brightYellow"],
  io: ["yellow", "yellow", "brightYellow", "brightYellow"],
} as const;

export type ThemeColor = string | undefined;

export type ThemeTokens = {
  [Key in keyof typeof TRUE_COLOR_TOKENS]: (typeof TRUE_COLOR_TOKENS)[Key] extends readonly string[]
    ? readonly ThemeColor[]
    : ThemeColor;
};

const NO_COLOR_TOKENS: ThemeTokens = {
  backgroundOuter: undefined,
  background: undefined,
  elevated: undefined,
  surface1: undefined,
  surface2: undefined,
  surface3: undefined,
  surface4: undefined,
  foreground: undefined,
  foregroundOnSurface: undefined,
  secondary: undefined,
  secondaryOnSurface: undefined,
  muted: undefined,
  mutedOnSurface: undefined,
  disabled: undefined,
  decoration: undefined,
  borderSubtle: undefined,
  border: undefined,
  borderStrong: undefined,
  primary: undefined,
  primaryText: undefined,
  accent: undefined,
  hover: undefined,
  selected: undefined,
  focus: undefined,
  infoBackground: undefined,
  warningBackground: undefined,
  dangerBackground: undefined,
  success: undefined,
  warning: undefined,
  danger: undefined,
  kunpeng: undefined,
  kunpengSecondary: undefined,
  copyBlue: [undefined, undefined, undefined, undefined, undefined],
  violet: [undefined, undefined, undefined, undefined, undefined],
  accumOrange: [undefined, undefined, undefined, undefined, undefined, undefined, undefined],
  ubGreen: [undefined, undefined, undefined, undefined, undefined],
  mteAmber: [undefined, undefined, undefined, undefined, undefined],
  cpu: [undefined, undefined, undefined, undefined],
  npu: [undefined, undefined, undefined, undefined],
  memory: [undefined, undefined, undefined, undefined],
  io: [undefined, undefined, undefined, undefined],
};

export function tokensFor(capabilities: TerminalCapabilities): ThemeTokens {
  if (capabilities.colorMode === "none") return NO_COLOR_TOKENS;
  if (capabilities.colorMode === "ansi16") return ANSI16_TOKENS;
  return TRUE_COLOR_TOKENS;
}

export const SPACE = {
  x1: 0,
  x2: 1,
  x3: 2,
  x4: 2,
  x5: 3,
  x6: 3,
  y1: 0,
  y2: 0,
  y3: 0,
  y4: 1,
  y5: 1,
  y6: 2,
} as const;
